esphome:
  name: livingroom-acbot3
  platformio_options:
    board_build.flash_mode: dio
    platform_packages:
      - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
    board_build.f_flash: 40000000L
    board_build.flash_size: 4MB
  on_boot:
    priority: 600
    then:
      - servo.write:
          id: updown
          level: 0
      - servo.write:
          id: power
          level: 0

preferences:
  flash_write_interval: 70s

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    #type: arduino
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

# Enable logging
logger:
  #level: VERY_VERBOSE
  logs:
    esp-idf: ERROR

<<: !include "secrets.yaml"

servo:
  - id: power
    output: power_servo_output
  - id: updown
    output: updown_servo_output

output:
  - platform: ledc
    id: power_servo_output
    pin: GPIO6
    frequency: 50Hz
  - platform: ledc
    id: updown_servo_output
    pin: GPIO7
    frequency: 50Hz

  - platform: ledc
    id: d0
    pin: GPIO5
    frequency: 50Hz
  - platform: ledc
    id: d1
    pin: GPIO4
    frequency: 50Hz
  - platform: ledc
    id: d2
    pin: GPIO10
    frequency: 50Hz

sensor:
  - platform: adc
    internal: true
    id: livingroom_ac_screen_lightval
    pin: 4
    name: AC Screen Photoresistor
    update_interval: 1s
    attenuation: auto

number:
  - platform: template
    internal: true
    name: AC Up/Down Servo
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: updown
            level: !lambda 'return x / 100.0;'
  - platform: template
    internal: true
    name: AC Power Servo
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: power
            level: !lambda 'return x / 100.0;'

button:
  - platform: template
    name: Living Room AC
    id: living_room_ac_power_toggle
    internal: true
    on_press:
      - servo.write:
          id: power
          level: 0.50
      - delay: 250ms
      - servo.write:
          id: power
          level: 0.0
      - delay: 250ms
  - platform: template
    name: Living Room AC Down
    id: living_room_ac_temp_down
    on_press:
      - servo.write:
          id: updown
          level: 0.20
      - delay: 250ms
      - servo.write:
          id: updown
          level: 0.0
      - delay: 250ms
  - platform: template
    name: Living Room AC Up
    id: living_room_ac_temp_up
    on_press:
      - servo.write:
          id: updown
          level: -0.45
      - delay: 250ms
      - servo.write:
          id: updown
          level: 0.0
      - delay: 250ms

switch:
  - platform: template
    id: living_room_ac
    icon: 'mdi:air-conditioner'
    name: "AC"
    lambda: |-
      if (id(livingroom_ac_screen_lightval).state > 0.08) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - button.press: living_room_ac_power_toggle
    turn_off_action:
      - button.press: living_room_ac_power_toggle

        #bluetooth_proxy:
        #  active: true
