name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - livingroom-acbot.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Create secrets.yaml
        run: |
          cp .github/workflows/secrets.yaml .
        shell: bash
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.8.0
        with:
          yaml_file: ${{ matrix.file }}
